#!/usr/bin/env python3
# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


"""Script to programmatically regenerate express_dsl_examples.md from active code.

Generates the A2UI Express model system prompt from the catalog schema,
compiles the weather forecast DSL sample using the compiler, and writes the
complete end-to-end trace as a markdown documentation file.
"""

import json
import os
import sys

# Support direct execution and locate the agent SDK packages
sys.path.insert(
    0,
    os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "..",
            "..",
            "..",
            "agent_sdks",
            "python",
            "a2ui_agent",
            "src",
        )
    ),
)

import json
from a2ui.core.catalog import Catalog
from a2ui.experimental.express.compiler import ExpressCompiler
from a2ui.experimental.express.prompt_generator import ExpressPromptGenerator

WEATHER_DSL = """<a2ui>
$/forecast = [{"day": "Monday", "icon": "https://img.icons8.com/color/48/000000/sun.png", "temp": "72°F / 55°F"}, {"day": "Tuesday", "icon": "https://img.icons8.com/color/48/000000/partly-cloudy-day.png", "temp": "68°F / 50°F"}, {"day": "Wednesday", "icon": "https://img.icons8.com/color/48/000000/rain.png", "temp": "60°F / 48°F"}, {"day": "Thursday", "icon": "https://img.icons8.com/color/48/000000/partly-cloudy-day.png", "temp": "65°F / 52°F"}, {"day": "Friday", "icon": "https://img.icons8.com/color/48/000000/sun.png", "temp": "70°F / 54°F"}]
root = Column([cityName, currentRow, divider, forecastList])
cityName = Text("New York")
currentRow = Row([currentTemp, currentIcon], "center", "center")
currentTemp = Text("68°F")
currentIcon = Image("https://img.icons8.com/color/96/000000/sun.png", "Sunny")
divider = Divider("horizontal")
forecastList = List(_template($/forecast, forecastItem), "vertical")
forecastItem = Row([itemDay, itemIcon, itemTemp], "spaceBetween", "center")
itemDay = Text($day)
itemIcon = Image($icon, "Weather icon")
itemTemp = Text($temp)
</a2ui>"""

USER_REQUEST = """Translate the following request into A2UI Express DSL wrapped inside <a2ui> and </a2ui> sentinels:

Generate a single 'createSurface' message with components inline with surfaceId 'main' for a weather forecast UI. It should have a 'Text' with the city name, "New York". Below it, a 'Row' with the current temperature as a 'Text' component ("68°F") and an 'Image' for the weather icon (e.g., a sun). Below that, a 'Divider'. Then, a 'List' component to display the 5-day forecast. Each item in the list should be a 'Row' with the day, an icon, and high/low temperatures.

REMINDER: You must output ONLY A2UI Express DSL wrapped in <a2ui> and </a2ui> sentinels. Do NOT output JSON or <a2ui-json> blocks under any circumstances. Directly generating JSON will fail compilation."""


def main():
    # Paths
    catalog_path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "..",
            "..",
            "v1_0",
            "catalogs",
            "basic",
            "catalog.json",
        )
    )
    output_path = os.path.abspath(
        os.path.join(
            os.path.dirname(__file__),
            "..",
            "express_dsl_examples.md",
        )
    )

    print(f"Generating system prompt from catalog: {catalog_path}...")
    with open(catalog_path, "r", encoding="utf-8") as f:
        catalog_dict = json.load(f)
    catalog = Catalog.from_json(catalog_dict, spec_version="0.9.1")
    prompt_generator = ExpressPromptGenerator(catalog)
    system_prompt = prompt_generator.generate_prompt()

    print("Compiling weather forecast Express DSL...")
    compiler = ExpressCompiler(catalog)
    compiled_dict = compiler.compile(
        WEATHER_DSL,
        surface_id="main",
        catalog_id="https://a2ui.org/specification/v1_0/catalogs/basic/catalog.json",
    )
    compiled_json_str = json.dumps(compiled_dict, indent=2)

    print(f"Constructing markdown content and writing to {output_path}...")
    markdown_content = f"""# A2UI Express DSL Strategy Generation Examples

This file documents a complete end-to-end trace of a generated sample from the baseline A2UI Express DSL evaluation run.
It includes the full system prompt (detailing layout instructions, syntax formats, and enums), the user request, the raw Express DSL output generated by the model, and the final compiled standard A2UI v1.0 JSON layout.

---

## The Input Prompts

### System Prompt Injected to Model:

````text
{system_prompt}
````

### User Request / Input:

```text
{USER_REQUEST}
```

---

## 3. Raw Model Output (A2UI Express DSL)

The model was instructed to output the UI using the optimized compact Express DSL notation wrapped inside `<a2ui>` and `</a2ui>` sentinel tags.

```text
{WEATHER_DSL}
```

---

## Compiled Standard A2UI v1.0 Layout Payload

The A2UI Express compiler parsed the compact DSL above, dynamically generated component IDs, constructed parent-child reference links, and resolved positional arguments to form a standard A2UI v1.0 `createSurface` message structure.

```json
{compiled_json_str}
```
"""

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(markdown_content)

    print("Documentation successfully regenerated!")


if __name__ == "__main__":
    main()
